### ISSUE TITLE
deprecation warning: Using Ember.$() has been deprecated, use `import jQuery from 'jquery';`

### ISSUE THREAD

**Issue by ghost** [rajasegar/ember-slide-push-menu#5]
Seeing this in version 1.0.0 (1.0.1 doesn't seem to be a legit version?). I'm using Ember 3.11.

`deprecate.js:120 DEPRECATION: Using Ember.$() has been deprecated, use `import jQuery from 'jquery';` instead [deprecation id: ember-views.curly-components.jquery-element] See https://emberjs.com/deprecations/v3.x#toc_jquery-apis for more details.
        at logDeprecationStackTrace (http://localhost:4200/assets/vendor.js:54731:23)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:54758:11)
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at http://localhost:4200/assets/lightworks-tuxedo.js:19533:9
        at HANDLERS.<computed> (http://localhost:4200/assets/vendor.js:54825:11)
        at invoke (http://localhost:4200/assets/vendor.js:54837:11)
        at deprecate (http://localhost:4200/assets/vendor.js:54796:30)
        at Object.get [as $] (http://localhost:4200/assets/vendor.js:74910:52)`

And if I add a breakpoint at the last frame from the above trace, I am here:

```
didInsertElement() {
      this._super(...arguments);
      Ember.$('body').addClass('cbp-spmenu-push');
},
```

Let me know if I can provide any more info!

**Comment by rajasegar** [comment]
This has been fixed in the latest version.
